name: Build and Publish

on:
  push:
    branches:
      - projecta-pack

permissions: 
  packages: write
  contents: read

env:
  PROJECT_PATH: ProjectA
  PROJECT_NAME: ProjectA
  DOTNET_VERSION: 6.x

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define variables for the loop
        projects: ["ProjectA/ProjectA.csproj", "ProjectB/ProjectB.csproj"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: |
          for project in "${{ matrix.projects }}"; do
            echo "Building $project"
            dotnet build --configuration Release $project
          done
          echo "This is iteration ${{ matrix.projects }}" 
      - name: Pack
        run: |
          for project in "${{ matrix.projects }}"; do
            echo "This is iteration ${{ matrix.projects }}"
            dotnet pack $project --configuration Release --output ./dist --no-build
          done
      - name: Publish to GitHub Packages 
        run: dotnet nuget push ./dist/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN1 }}  --source "https://nuget.pkg.github.com/LexCheck/index.json" --skip-duplicate
